#!/usr/bin/env python3
"""
DeePC torque controller for reach.

Mirrors the ROS topic surface of `pi_control_gap.py`:
- Subscribe: `/digital_twin/joint_differences` (JointState.position[0:7]) as y(t)
- Subscribe: `deepc/py_controller` (JointState.effort[0:7]) as u(t) for u_past
- Publish:   `deepc/py_controller` (JointState.effort[0:7]) torque command

Additionally publishes:
- `/deepc/y_pred` (JointState.position[0:7]) = next-step predicted y (diff)

The DeePC training data is reconstructed from a saved Hankel `.npz`
generated by `build_hankel_from_csv.py`, where:
- u(t) = effort_1..7 (torques)
- y(t) = diff_1..7 (joint differences)
"""

from __future__ import annotations

import json
import sys
import time
import threading
from collections import deque
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Deque, Optional, Tuple, cast

import numpy as np
import rclpy
from rclpy.node import Node
from sensor_msgs.msg import JointState

# Ensure local `pydeepc/` package is importable when this file is executed as a script.
_THIS_DIR = Path(__file__).resolve().parent
if str(_THIS_DIR) not in sys.path:
    sys.path.insert(0, str(_THIS_DIR))

from pydeepc import DeePC  # noqa: E402
from pydeepc.utils import Data  # noqa: E402

try:
    import cvxpy as cp  # noqa: E402
except Exception as exc:  # pragma: no cover
    raise RuntimeError(
        "cvxpy is required to run DeePC. Ensure it is installed in your ROS python env."
    ) from exc


NUM_JOINTS = 7


@dataclass(frozen=True)
class HankelMeta:
    tini: int
    horizon: int
    order: int
    u_dim: int
    y_dim: int


def _load_hankel_npz(
    path: Path,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, HankelMeta]:
    data = np.load(path)
    meta_raw = json.loads(data["meta"].item())

    tini = int(meta_raw["tini"])
    horizon = int(meta_raw["horizon"])
    order = int(meta_raw["order"])
    if order != tini + horizon:
        raise ValueError(f"Invalid meta: order={order} but tini+horizon={tini+horizon}")

    u_dim = len(meta_raw.get("u_columns", [])) or NUM_JOINTS
    y_dim = len(meta_raw.get("y_columns", [])) or NUM_JOINTS

    # Direct DeePC partitions (what we actually use online).
    Up = np.asarray(data["Up"], dtype=np.float64)
    Uf = np.asarray(data["Uf"], dtype=np.float64)
    Yp = np.asarray(data["Yp"], dtype=np.float64)
    Yf = np.asarray(data["Yf"], dtype=np.float64)

    return Up, Uf, Yp, Yf, HankelMeta(
        tini=tini, horizon=horizon, order=order, u_dim=u_dim, y_dim=y_dim
    )


class DeePCControlGap(Node):
    def __init__(self) -> None:
        super().__init__("deepc_control_gap")
        Q_array = [4*174.0, 4*32.7, 4*186.1, 4*89.0, 4*294.5, 4*2940.4, 4*85.0]
        # --- Parameters (tunable at runtime) ---
        default_hankel_path = _THIS_DIR / "10Hz_1346_p_5_300_hankel_tini5_N15.npz"
        self.declare_parameter("hankel_path", str(default_hankel_path))
        self.declare_parameter("dt", 0.1)  # 10 Hz
        self.declare_parameter("solver", "MOSEK")  # will auto-fallback if unavailable
        # K-step playback: apply the first K inputs from each horizon solution open-loop.
        self.declare_parameter("apply_steps", 1)
        # Start computing the next plan when the current segment is about to end.
        self.declare_parameter("refill_margin_steps", 0)
        self.declare_parameter("lambda_g", 80)
        # Regularizer that enables DeePC's internal past-output slack (slack_y).
        # Set to 0.0 to keep a hard match on y_ini (slack_y ~= 0).
        self.declare_parameter("lambda_y", 90000.0)
        self.declare_parameter("u_weight", 0.0)
        # Per-joint output cost weights (diagonal of Q in y'Qy). Defaults to identity.
        self.declare_parameter("Q_diag", Q_array)
        # Terminal output constraint: enforce last predicted y to be close to 0:
        # -y_terminal_eps <= y[-1, j] <= y_terminal_eps
        # Set <= 0 to disable.
        self.declare_parameter("y_terminal_eps", 2.0)
        # Per-joint torque limits (Nm). Applied as -u_limits[j] <= u[:,j] <= u_limits[j].
        # Default all joints to 2.0 Nm.
        self.declare_parameter("u_limits", [6.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0])
        # Backward-compatible scalar limit (used only if u_limits is invalid/missing).
        self.declare_parameter("u_limit", 0.0)  # <=0 disables

        self._dt = float(self.get_parameter("dt").value)
        if self._dt <= 0:
            raise ValueError("Parameter dt must be > 0")

        self._apply_steps = int(self.get_parameter("apply_steps").value)
        self._refill_margin_steps = int(self.get_parameter("refill_margin_steps").value)
        if self._apply_steps < 1:
            raise ValueError("Parameter apply_steps must be >= 1")
        if self._refill_margin_steps < 0:
            raise ValueError("Parameter refill_margin_steps must be >= 0")

        # --- Latest measurements / commands ---
        self._latest_y: np.ndarray = np.zeros(NUM_JOINTS, dtype=np.float64)
        self._have_y: bool = False

        self._latest_u: np.ndarray = np.zeros(NUM_JOINTS, dtype=np.float64)
        self._have_u: bool = False
        self._last_published_u: np.ndarray = np.zeros(NUM_JOINTS, dtype=np.float64)

        # --- ROS I/O (mirror PI) ---
        self._diff_sub = self.create_subscription(
            JointState,
            "/digital_twin/joint_differences",
            self._diff_cb,
            10,
        )
        self._u_sub = self.create_subscription(
            JointState,
            "deepc/py_controller",
            self._u_cb,
            10,
        )

        self._tau_pub = self.create_publisher(JointState, "deepc/py_controller", 10)
        self._y_pred_pub = self.create_publisher(JointState, "/deepc/y_pred", 10)

        # --- Load Hankel + build DeePC problem ---
        hankel_path = Path(str(self.get_parameter("hankel_path").value)).expanduser()
        if not hankel_path.is_absolute():
            hankel_path = (_THIS_DIR / hankel_path).resolve()

        Up, Uf, Yp, Yf, meta = _load_hankel_npz(hankel_path)
        if meta.u_dim != NUM_JOINTS or meta.y_dim != NUM_JOINTS:
            raise ValueError(
                f"Hankel dims do not match controller: u_dim={meta.u_dim}, y_dim={meta.y_dim}, "
                f"expected {NUM_JOINTS}"
            )

        # Sanity-check shapes to catch accidental mismatched `.npz` files.
        if Up.shape[0] != meta.tini * meta.u_dim:
            raise ValueError(
                f"Up rows mismatch: {Up.shape[0]} != tini*u_dim={meta.tini * meta.u_dim}"
            )
        if Yp.shape[0] != meta.tini * meta.y_dim:
            raise ValueError(
                f"Yp rows mismatch: {Yp.shape[0]} != tini*y_dim={meta.tini * meta.y_dim}"
            )
        if Uf.shape[0] != meta.horizon * meta.u_dim:
            raise ValueError(
                f"Uf rows mismatch: {Uf.shape[0]} != horizon*u_dim={meta.horizon * meta.u_dim}"
            )
        if Yf.shape[0] != meta.horizon * meta.y_dim:
            raise ValueError(
                f"Yf rows mismatch: {Yf.shape[0]} != horizon*y_dim={meta.horizon * meta.y_dim}"
            )

        # DeePC expects to own Hankel partitions; we load them directly from the `.npz`.
        # We still need to satisfy DeePC's constructor shape checks (it expects enough T).
        g_dim = int(Up.shape[1])  # number of columns in the Hankel partitions
        T_dummy = g_dim + meta.tini + meta.horizon - 1  # ensures g_dim = T - Tini - N + 1
        u_dummy = np.zeros((T_dummy, meta.u_dim), dtype=np.float64)
        y_dummy = np.zeros((T_dummy, meta.y_dim), dtype=np.float64)

        self._deepc = DeePC(Data(u_dummy, y_dummy), Tini=meta.tini, horizon=meta.horizon)
        self._deepc.Up = Up
        self._deepc.Uf = Uf
        self._deepc.Yp = Yp
        self._deepc.Yf = Yf
        self._deepc.M = meta.u_dim
        self._deepc.P = meta.y_dim
        self._deepc.T = T_dummy
        # pydeepc internally treats this as optional; typing in the library is stricter than reality.
        cast(Any, self._deepc).optimization_problem = None  # force rebuild with loaded partitions
        self._tini = meta.tini
        self._horizon = meta.horizon

        # Validate playback params against the horizon.
        if self._apply_steps > self._horizon:
            self.get_logger().warn(
                f"apply_steps={self._apply_steps} > horizon={self._horizon}; clamping to horizon."
            )
            self._apply_steps = self._horizon
        if self._refill_margin_steps > self._apply_steps:
            self.get_logger().warn(
                f"refill_margin_steps={self._refill_margin_steps} > apply_steps={self._apply_steps}; clamping."
            )
            self._refill_margin_steps = self._apply_steps

        lambda_g = float(self.get_parameter("lambda_g").value)
        lambda_y = float(self.get_parameter("lambda_y").value)
        u_weight = float(self.get_parameter("u_weight").value)
        u_limit_scalar = float(self.get_parameter("u_limit").value)
        u_limits_param = self.get_parameter("u_limits").value
        q_diag_param = self.get_parameter("Q_diag").value
        y_terminal_eps = float(self.get_parameter("y_terminal_eps").value)
        # rclpy param value can be list/tuple depending on how it was set.
        try:
            u_limits = [float(x) for x in list(u_limits_param)]
        except Exception:
            u_limits = []
        if len(u_limits) != NUM_JOINTS:
            u_limits = []
        if any((not np.isfinite(x)) or x <= 0.0 for x in u_limits):
            u_limits = []
        if not u_limits and (not np.isfinite(u_limit_scalar) or u_limit_scalar <= 0.0):
            self.get_logger().warn(
                "Torque limits disabled (u_limits invalid and u_limit <= 0).",
                throttle_duration_sec=10.0,
            )

        # Build Q (7x7 diagonal) from a per-joint weight vector; fallback to identity on invalid input.
        try:
            q_diag = np.asarray([float(x) for x in list(q_diag_param)], dtype=np.float64)
        except Exception:
            q_diag = np.ones(NUM_JOINTS, dtype=np.float64)
        if q_diag.shape != (NUM_JOINTS,) or (not np.all(np.isfinite(q_diag))) or np.any(q_diag < 0.0):
            self.get_logger().warn("Invalid Q_diag; falling back to identity weights.")
            q_diag = np.ones(NUM_JOINTS, dtype=np.float64)
        Q = np.diag(q_diag)  # 7x7 diagonal matrix (currently identity by default)

        def loss_fn(u: cp.Variable, y: cp.Variable) -> cp.Expression:
            # y has shape (horizon, 7). For diagonal Q, sum_t y_t'Qy_t reduces to a
            # weighted sum of squares per joint across the horizon.
            y_cost = cp.sum(cp.multiply(q_diag, cp.square(y)))
            return y_cost  # + u_weight * cp.sum_squares(u)

        def constraints_fn(u: cp.Variable, y: cp.Variable):
            constraints = []

            # Torque limits (existing behavior, but we keep a single return path).
            if u_limits:
                for j, lim in enumerate(u_limits):
                    constraints.append(u[:, j] <= lim)
                    constraints.append(u[:, j] >= -lim)
            elif u_limit_scalar and u_limit_scalar > 0.0:
                constraints += [u <= u_limit_scalar, u >= -u_limit_scalar]

            # Terminal output close-to-zero constraint (optional).
            if np.isfinite(y_terminal_eps) and y_terminal_eps > 0.0:
                constraints += [y[-1, :] <= y_terminal_eps, y[-1, :] >= -y_terminal_eps]

            return constraints

        self._deepc.build_problem(
            build_loss=loss_fn,
            build_constraints=constraints_fn,
            lambda_g=lambda_g,
            lambda_y=lambda_y,
        )

        # --- Online buffers (u_past / y_past) ---
        self._u_hist: Deque[np.ndarray] = deque(maxlen=self._tini)
        self._y_hist: Deque[np.ndarray] = deque(maxlen=self._tini)

        # --- Plan buffers (active/pending) ---
        self._plan_lock = threading.Lock()
        self._active_u_plan: Optional[np.ndarray] = None  # (horizon, 7)
        self._active_y_plan: Optional[np.ndarray] = None  # (horizon, 7)
        self._active_idx: int = 0
        self._segment_remaining: int = 0

        self._pending_ready: bool = False
        self._pending_u_plan: Optional[np.ndarray] = None
        self._pending_y_plan: Optional[np.ndarray] = None

        self._worker_running: bool = False
        self._shutdown_event = threading.Event()

        # --- Timer ---
        self._timer = self.create_timer(self._dt, self._tick)

        # throttle for “waiting for data” logs
        self._last_wait_log_s: float = 0.0

        self.get_logger().info(
            f"DeePCControlGap ready | dt={self._dt:.3f}s ({1.0/self._dt:.1f} Hz) | "
            f"Tini={self._tini}, horizon={self._horizon} | "
            f"sub /digital_twin/joint_differences + deepc/py_controller | pub deepc/py_controller + /deepc/y_pred"
        )

    def destroy_node(self) -> bool:
        # Signal worker threads to stop (best-effort).
        self._shutdown_event.set()
        return super().destroy_node()

    # --- Callbacks ---
    def _diff_cb(self, msg: JointState) -> None:
        if len(msg.position) < NUM_JOINTS:
            self.get_logger().warn(
                f"Received diff vector of size {len(msg.position)}, expected {NUM_JOINTS}"
            )
            return
        self._latest_y = np.asarray(msg.position[:NUM_JOINTS], dtype=np.float64)
        self._have_y = True

    def _u_cb(self, msg: JointState) -> None:
        if not msg.effort or len(msg.effort) < NUM_JOINTS:
            return
        self._latest_u = np.asarray(msg.effort[:NUM_JOINTS], dtype=np.float64)
        self._have_u = True

    def _maybe_start_solve_worker(self) -> None:
        """Start a background solve if needed and no worker is currently running."""
        if self._shutdown_event.is_set():
            return
        if len(self._u_hist) < self._tini or len(self._y_hist) < self._tini:
            return

        with self._plan_lock:
            if self._worker_running:
                return

            need_plan_soon = (
                (self._active_u_plan is None)
                or (self._segment_remaining <= self._refill_margin_steps)
            )
            need = (not self._pending_ready) and need_plan_soon
            if not need:
                return
            self._worker_running = True

        # Snapshot past window outside the lock.
        u_ini = np.stack(list(self._u_hist), axis=0)
        y_ini = np.stack(list(self._y_hist), axis=0)
        solver = str(self.get_parameter("solver").value)

        thread = threading.Thread(
            target=self._solve_worker,
            args=(u_ini, y_ini, solver),
            daemon=True,
        )
        thread.start()

    def _solve_worker(self, u_ini: np.ndarray, y_ini: np.ndarray, solver: str) -> None:
        """Solve DeePC in the background and populate the pending plan on success."""
        try:
            ini_data = Data(u_ini, y_ini)
            solve_start = time.perf_counter()
            u_opt, info = self._deepc.solve(
                data_ini=ini_data,
                solver=solver,
                warm_start=True,
                verbose=False,
            )
            solve_dt = time.perf_counter() - solve_start

            status = None
            try:
                prob = cast(Any, self._deepc).optimization_problem.problem
                status = getattr(prob, "status", None)
            except Exception:
                status = None

            # Budget policy per plan: if solve exceeds dt or is non-optimal, don't commit it.
            if solve_dt > 10 * self._dt:
                self.get_logger().warn(
                    f"DeePC solve exceeded budget: {solve_dt*1e3:.1f}ms > {self._dt*1e3:.1f}ms "
                    f"(solver={solver}, status={status}). Dropping plan.",
                    throttle_duration_sec=1.0,
                )
                return
            if status not in (cp.OPTIMAL, cp.OPTIMAL_INACCURATE):
                self.get_logger().warn(
                    f"DeePC solve non-optimal status={status} (solver={solver}). Dropping plan.",
                    throttle_duration_sec=1.0,
                )
                return

            # Extract predicted y trajectory if available.
            y_plan: Optional[np.ndarray] = None
            try:
                variables = cast(Any, info.get("variables"))
                y_var = getattr(variables, "y", None)
                y_val = getattr(y_var, "value", None)
                if y_val is not None:
                    y_plan = np.asarray(y_val, dtype=np.float64)
            except Exception:
                y_plan = None

            # Commit pending plan.
            with self._plan_lock:
                if self._shutdown_event.is_set():
                    return
                self._pending_u_plan = np.asarray(u_opt, dtype=np.float64)
                self._pending_y_plan = y_plan
                self._pending_ready = True
        except Exception as exc:
            status = None
            try:
                prob = cast(Any, self._deepc).optimization_problem.problem
                status = getattr(prob, "status", None)
            except Exception:
                status = None
            self.get_logger().warn(
                f"DeePC solve failed (solver={solver}, status={status}). Error: {exc}",
                throttle_duration_sec=1.0,
            )
        finally:
            with self._plan_lock:
                self._worker_running = False

    # --- Control tick ---
    def _tick(self) -> None:
        if not self._have_y:
            now_s = self.get_clock().now().nanoseconds * 1e-9
            if now_s - self._last_wait_log_s > 5.0:
                self.get_logger().info("Waiting for /digital_twin/joint_differences ...")
                self._last_wait_log_s = now_s
            return

        # Use the latest commanded torque as u(t). If we haven't received any torque yet,
        # treat it as zeros until the first command arrives.
        u_t = self._latest_u if self._have_u else np.zeros(NUM_JOINTS, dtype=np.float64)
        y_t = self._latest_y

        self._u_hist.append(u_t.copy())
        self._y_hist.append(y_t.copy())

        if len(self._u_hist) < self._tini or len(self._y_hist) < self._tini:
            # Not enough past data yet; publish nothing (PI-like behavior).
            now_s = self.get_clock().now().nanoseconds * 1e-9
            if now_s - self._last_wait_log_s > 2.0:
                self.get_logger().info(
                    f"Filling DeePC past window: {len(self._y_hist)}/{self._tini} samples"
                )
                self._last_wait_log_s = now_s
            return

        # Select command to publish from the active plan (execute exactly K steps open-loop).
        u_cmd: Optional[np.ndarray] = None
        y_cmd: Optional[np.ndarray] = None
        with self._plan_lock:
            if self._active_u_plan is not None and self._segment_remaining > 0:
                # Continue executing the current segment.
                idx = min(self._active_idx, self._horizon - 1)
                u_cmd = self._active_u_plan[idx]
                if self._active_y_plan is not None:
                    y_cmd = self._active_y_plan[idx]
                self._active_idx = min(self._active_idx + 1, self._horizon)
                self._segment_remaining -= 1
            else:
                # Segment ended; swap in a new plan only at this boundary.
                if self._pending_ready and self._pending_u_plan is not None:
                    active_u_plan = self._pending_u_plan
                    active_y_plan = self._pending_y_plan
                    self._active_u_plan = active_u_plan
                    self._active_y_plan = active_y_plan
                    self._pending_u_plan = None
                    self._pending_y_plan = None
                    self._pending_ready = False
                    self._active_idx = 0
                    self._segment_remaining = self._apply_steps

                    idx = 0
                    u_cmd = active_u_plan[idx]
                    if active_y_plan is not None:
                        y_cmd = active_y_plan[idx]
                    self._active_idx = 1
                    self._segment_remaining -= 1
                elif self._active_u_plan is not None:
                    # No pending plan; hold the last torque from the previous plan.
                    u_cmd = self._active_u_plan[-1]
                    if self._active_y_plan is not None:
                        y_cmd = self._active_y_plan[-1]

        if u_cmd is None:
            # No plan available yet; publish zero torque.
            self._publish_fallback_zero()
        else:
            #u_cmd[0] = 1.0*u_cmd[0]
            #u_cmd[1] = 0.0*u_cmd[1]
            #u_cmd[2] = 0.0
            #u_cmd[3] = 0.0
            #u_cmd[4] = 0.0
            #u_cmd[5] = 0.0
            #u_cmd[6] = 0.0
            self._publish_tau(np.asarray(u_cmd, dtype=np.float64))
            if y_cmd is not None:
                self._publish_y_pred(np.asarray(y_cmd, dtype=np.float64))

        # Kick off background solve if we are close to needing the next plan.
        self._maybe_start_solve_worker()

    def _publish_tau(self, tau_7: np.ndarray) -> None:
        out = JointState()
        out.header.stamp = self.get_clock().now().to_msg()
        out.name = [f"tau_{i+1}" for i in range(NUM_JOINTS)]
        out.effort = tau_7.tolist()
        self._tau_pub.publish(out)

        # Update internal last command immediately (independent of ROS echo timing).
        self._last_published_u = tau_7.copy()
        self._latest_u = tau_7.copy()
        self._have_u = True

    def _publish_y_pred(self, y_pred_7: np.ndarray) -> None:
        out = JointState()
        out.header.stamp = self.get_clock().now().to_msg()
        out.name = [f"y_pred_{i+1}" for i in range(NUM_JOINTS)]
        out.position = y_pred_7.tolist()
        self._y_pred_pub.publish(out)

    def _publish_fallback_zero(self) -> None:
        self._publish_tau(np.zeros(NUM_JOINTS, dtype=np.float64))


def main() -> None:
    rclpy.init()
    node = DeePCControlGap()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        node.get_logger().info("Shutting down DeePCControlGap...")
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
